version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command:  /nsqd --broadcast-address=nsqd --lookupd-tcp-address=172.19.0.1:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4151:4151"
      - "4150:4150"
    links: 
      - nsqlookupd
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=172.19.0.1:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
    links: 
      - nsqlookupd
      - nsqd

  nsq-consumer:
    build:
      context: ./
      dockerfile: consumer.Dockerfile
    image: nsq-consumer
    container_name: nsq-consumer
    volumes:
      - type: bind
        source: ./consumer.js
        target: /app/consumer.js
  nsq-producer:
    build:
      context: ./
      dockerfile: producer.Dockerfile
    image: nsq-producer
    container_name: nsq-producer
    depends_on:
      - nsq-consumer
    volumes:
      - type: bind
        source: ./producer.js
        target: /app/producer.js